# Generated by Django 5.0.4 on 2024-05-11 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name': 'Attempt', 'verbose_name_plural': 'Attempts'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['text'], 'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['text'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['name'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('text', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('text', 'quiz')},
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('name', 'creator')},
        ),
    ]
